### ISSUE TITLE
simplesnap not working from cron but from commandline

### ISSUE THREAD

**Issue by psychoticbeef** [jgoerzen/simplesnap#10]
Hi,

I only get the following log entry when running simplesnap from cron (debian jessie):

`Feb  7 04:10:01 thost simplesnap[14800]: Invoked as: /usr/sbin/simplesnap --host shost --setname shost --store home/shost`

Nothing more. The sync does not work then. I run the script via cron as root.

When I manually run /usr/sbin/simplesnap, it works just fine. Do you have any idea what the cause may be? My authorized_keys on thost looks like this:
`command="/usr/sbin/simplesnapwrap",no-port-forwarding,no-X11-forwarding,no-pty ssh-rsa [rest omitted]`.

Are there maybe required paths missing?

**Comment by abrose** [comment]
Hello,

did you manage to fix this issue? I'm experiencing the same problem - when I run the command as root in the console everything works as expected but if I put the same command into the crontab it fails and sends the following message to /var/mail/root:

```
/usr/sbin/simplesnap: Zeile 168: zfs: Befehl nicht gefunden
```

Regards,
Al

**Comment by pongraczi** [comment]
Hi,
In crontab, the PATH is not known, you must specify it, like this:

---------------- >8  cut here  8< --------------------

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

*/2 * * * * /usr/local/bin/vpn_autoconnect.sh
30 00 * * * /usr/local/sbin/simplesnap --host remotehost --setname dailybackup --store tank/simplesnap --sshcmd "ssh -i /root/.ssh/id_rsa_simplesnap"

**Comment by abrose** [comment]
Hi,

oh, that's obvious. Haven't thought about that.

Thx a lot!
Al
