### ISSUE TITLE
skip snapshot if `com.sun:auto-snapshot=false`

### ISSUE THREAD

**Issue by HRio** [jgoerzen/simplesnap#15]
*feature-request*

It would be nice if `com.sun:auto-snapshot=false` would have the same effect as `org.complete.simplesnap:exclude=on`

The original Sun documentation and https://github.com/zfsonlinux/zfs-auto-snapshot uses this to disable snapshotting.

**Comment by HRio** [comment]
Something like this perhaps?
```diff
--- a/simplesnapwrap
+++ b/simplesnapwrap
@@ -18,7 +18,7 @@
 set -e
 ZFSCMD=/sbin/zfs
 ZFS=runzfs
-EXCLUDEPROP="org.complete.simplesnap:exclude"
+EXCLUDEPROP="org.complete.simplesnap:exclude,com.sun:auto-snapshot"

 logit () {
    logger -p info -t "`basename $0`[$$]" "$1"
@@ -76,7 +76,7 @@ if [ "$1" = "reinvoked" ]; then
     "listfs")
        logit "Listing ZFS datasets without ${EXCLUDEPROP}=on"
        $ZFS list -t filesystem,volume -o "name,${EXCLUDEPROP}" -H | \
-          $GREP -v $'\ton$' | $SED $'s/\t.*$//'
+          $GREP -E -v $'\ton\t|\tfalse$' | $SED $'s/\t.*$//'
        ;;
     "sendback")
        # Next lines shared with reap
```

**Comment by jgoerzen** [comment]
I appreciate this report, but I believe this violates the principle of least surprise.  Whether or not a person wants some mechanism to make historic snapshots of a filesystem is, in some cases, orthogonal to whether or not that filesystem should be backed up.  This could result in backups silently being skipped on existing systems as well.

**Comment by HRio** [comment]
OK, for me the surprise was that VM swap zvols (marked with com.sun:auto-snapshot=false) ended up being snapshotted and transfered :smile:
