### ISSUE TITLE
Add stream resumption support

### ISSUE THREAD

**Issue by jplitza** [jgoerzen/simplesnap#19]
Newer ZFS versions support resuming an aborted `zfs send` stream if both parties support it.
One would use `zfs send -t $TOKEN` to continue an aborted stream, where `$TOKEN` is the value of the dataset property `receive_resume_token` on the receiving side. This token, on the other hand, is set by `zfs receive -s` if it aborts for whatever reason.

My use case for the feature is a crappy DSL line with daily forced disconnection. If a backup batch becomes too large, it cannot be sent in one day and thus has to start over after the disconnect. But unexpected system shutdown during backup etc. can also profit from this feature.

**Comment by jgoerzen** [comment]
This is a good idea.  It will require a little work so I’d gladly entertain a patch to implement it (time is tight for me just now)

**Comment by jplitza** [comment]
So after implementing this for tests (c39030991dc1925b7ed3358f5a78f36072846ff3), it turns out that this feature's support in ZFS seems to be suboptimal. Resumption streams sometimes cannot be received at all (some kernel-level error that `zfs receives` incorrectly blames on the module version), sometimes finish successfully without reaching the snapshot that was specified in the original `zfs send`. Both problems make this too unreliable at the moment to use in production, so I'm closing this issue for now.
